import type { BlogPost } from '@/types'

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Clean Architecture with ASP.NET Core',
    excerpt: 'How to structure enterprise applications using Clean Architecture principles with .NET.',
    content: 'Lorem ipsum dolor sit amet...',
    tags: ['Architecture', '.NET', 'Clean Code'],
    readingTime: 8,
    date: '2024-03-15',
    author: 'Senior Engineer',
    slug: 'clean-architecture-aspnet-core',
  },
  {
    id: '2',
    title: 'Building Real-Time Apps with SignalR',
    excerpt: 'A deep dive into real-time communication using SignalR and React.',
    content: 'Lorem ipsum dolor sit amet...',
    tags: ['Real-Time', 'SignalR', 'React'],
    readingTime: 6,
    date: '2024-02-20',
    author: 'Senior Engineer',
    slug: 'real-time-apps-signalr',
  },
  {
    id: '3',
    title: 'CQRS Pattern in Practice',
    excerpt: 'Implementing Command Query Responsibility Segregation in .NET applications.',
    content: 'Lorem ipsum dolor sit amet...',
    tags: ['CQRS', 'Patterns', '.NET'],
    readingTime: 10,
    date: '2024-01-10',
    author: 'Senior Engineer',
    slug: 'cqrs-pattern-practice',
  },
  {
    id: '4',
    title: 'Microservices vs Monolith: Making the Right Choice',
    excerpt: 'When to choose microservices architecture and when to stick with a monolith.',
    content: 'Lorem ipsum dolor sit amet...',
    tags: ['Architecture', 'Microservices', 'Best Practices'],
    readingTime: 7,
    date: '2023-12-05',
    author: 'Senior Engineer',
    slug: 'microservices-vs-monolith',
  },
  {
    id: '5',
    title: 'Optimizing React Performance',
    excerpt: 'Techniques for building high-performance React applications at scale.',
    content: 'Lorem ipsum dolor sit amet...',
    tags: ['React', 'Performance', 'TypeScript'],
    readingTime: 9,
    date: '2023-11-18',
    author: 'Senior Engineer',
    slug: 'optimizing-react-performance',
  },
]
