import type { Project } from '@/types'

export const PROJECTS: Project[] = [
  {
    id: 'humanitarian-platform',
    title: 'Humanitarian Platform',
    summary: 'A full-stack platform connecting volunteers with humanitarian organizations.',
    description: 'Built a comprehensive platform that streamlines volunteer coordination, resource management, and disaster response logistics for humanitarian organizations worldwide.',
    challenge: 'Coordinating volunteers and resources across multiple organizations and locations during crisis situations required a robust, scalable system with real-time capabilities.',
    solution: 'Implemented Clean Architecture with CQRS pattern, ensuring separation of concerns and maintainability. Used SignalR for real-time updates and MediatR for command/query handling.',
    architecture: ['Clean Architecture', 'CQRS', 'MediatR', 'SignalR', 'Outbox Pattern'],
    technologies: ['React', 'TypeScript', 'ASP.NET Core', 'SQL Server', 'Azure', 'SignalR'],
    tags: ['Full Stack', 'Real-time', 'Cloud'],
    category: 'Full Stack',
    image: '/projects/humanitarian.jpg',
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    lessons: [
      'CQRS pattern significantly improved code maintainability',
      'Real-time updates were critical for volunteer coordination',
      'Outbox pattern ensured message reliability',
    ],
  },
  {
    id: 'clinic-management',
    title: 'Clinic Management System',
    summary: 'Enterprise clinic management with EHR, scheduling, and billing integration.',
    description: 'Developed a comprehensive clinic management system featuring electronic health records, intelligent scheduling, insurance billing, and analytics dashboard.',
    challenge: 'Managing sensitive patient data while ensuring HIPAA compliance, handling complex scheduling logic, and integrating with multiple insurance providers.',
    solution: 'Applied Domain-Driven Design with a microservices architecture. Used Identity Server for authentication and JWT for API security.',
    architecture: ['Microservices', 'DDD', 'Identity Server', 'JWT', 'Repository Pattern'],
    technologies: ['Angular', 'TypeScript', 'ASP.NET Core', 'PostgreSQL', 'Docker', 'Redis'],
    tags: ['Enterprise', 'Healthcare', 'Security'],
    category: 'Enterprise',
    githubUrl: 'https://github.com',
    lessons: [
      'DDD helped model complex medical domain accurately',
      'Microservices enabled independent team workflows',
      'Caching layer significantly improved patient lookup performance',
    ],
  },
  {
    id: 'ecommerce-platform',
    title: 'E-Commerce Platform',
    summary: 'Scalable e-commerce solution with microservices and event-driven architecture.',
    description: 'Built a high-performance e-commerce platform handling thousands of transactions per minute with inventory management, payment processing, and order fulfillment.',
    challenge: 'Handling high transaction volumes while maintaining data consistency across distributed services during peak shopping events.',
    solution: 'Implemented Event-Driven Architecture with Azure Service Bus for async communication. Used Stripe for payment processing and Redis for session management.',
    architecture: ['Event-Driven', 'Microservices', 'Clean Architecture', 'Background Workers'],
    technologies: ['React', 'Next.js', 'ASP.NET Core', 'MongoDB', 'Azure', 'Stripe'],
    tags: ['E-Commerce', 'High Traffic', 'Microservices'],
    category: 'Full Stack',
    githubUrl: 'https://github.com',
    liveUrl: 'https://example.com',
    lessons: [
      'Eventual consistency requires careful UX design',
      'Background workers critical for order fulfillment',
      'Caching strategy massively impacted performance',
    ],
  },
  {
    id: 'portfolio-cms',
    title: 'Portfolio CMS',
    summary: 'Headless CMS with drag-and-drop content management and dynamic theming.',
    description: 'Created a headless CMS with a visual page builder, allowing non-technical users to create and manage portfolio content with dynamic themes.',
    challenge: 'Building an intuitive drag-and-drop interface while supporting custom themes and maintaining clean API contracts.',
    solution: 'Used React DnD for the page builder, implemented a plugin architecture for themes, and built a RESTful API with ASP.NET Core.',
    architecture: ['Clean Architecture', 'Plugin Architecture', 'REST API', 'Caching'],
    technologies: ['React', 'TypeScript', 'ASP.NET Core', 'PostgreSQL', 'Redis', 'Docker'],
    tags: ['CMS', 'Tooling', 'Full Stack'],
    category: 'Full Stack',
    githubUrl: 'https://github.com',
    lessons: [
      'Plugin architecture enabled extensibility',
      'Caching critical for CMS performance',
      'Drag-and-drop required careful state management',
    ],
  },
  {
    id: 'flutter-app',
    title: 'Flutter Application',
    summary: 'Cross-platform mobile app with offline-first architecture and real-time sync.',
    description: 'Developed a cross-platform mobile application with offline capabilities, real-time synchronization, and native platform features.',
    challenge: 'Ensuring data consistency across offline/online transitions while providing a native-feeling experience on both iOS and Android.',
    solution: 'Used Bloc pattern for state management, SQLite for offline storage, and implemented a sync engine with conflict resolution.',
    architecture: ['Bloc Pattern', 'Offline-First', 'Sync Engine', 'Clean Architecture'],
    technologies: ['Flutter', 'Dart', 'Firebase', 'SQLite', 'REST API'],
    tags: ['Mobile', 'Cross-Platform', 'Offline'],
    category: 'Mobile',
    githubUrl: 'https://github.com',
    lessons: [
      'Offline-first architecture requires careful planning',
      'Conflict resolution is critical for data integrity',
      'Bloc pattern provided clean state management',
    ],
  },
]

export const PROJECT_CATEGORIES = ['All', 'Full Stack', 'Enterprise', 'Mobile', 'Tooling']
